=== codescape/bitvunit/bitvunit-core/src/main/resources/ruleset-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://bitvunit.codescape.de/ruleset/1.0"
           targetNamespace="http://bitvunit.codescape.de/ruleset/1.0" elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <xs:element name="ruleset">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Root element of the XML document that contains a list of rule elements that shall be used.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="rule" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="description" type="xs:string">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Optional element that contains a description of the document and it's contained rules.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="rule">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Element that describes a rule through the full qualified class name of the rule.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="class" type="xs:NMTOKEN" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== codescape/bitvunit/bitvunit-samples/src/test/resources/rulesets/label-rules.xml
<?xml version="1.0" encoding="utf-8"?>
<ruleset xmlns="http://bitvunit.codescape.de/ruleset/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://bitvunit.codescape.de/ruleset/1.0 ../ruleset-schema.xsd">

    <description>Set of all rules used to demo custom rule sets.</description>

    <rule class="de.codescape.bitvunit.rule.forms.LabelContainsTextRule"/>
    <rule class="de.codescape.bitvunit.rule.forms.LabelForInputFieldRule"/>
    <rule class="de.codescape.bitvunit.rule.forms.LabelForSelectTagRule"/>
    <rule class="de.codescape.bitvunit.rule.forms.LabelForTextareaRule"/>
    <rule class="de.codescape.bitvunit.rule.forms.LabelWithoutFormElementRule"/>
    <rule class="de.codescape.bitvunit.rule.forms.UniqueLabelForFormElementRule"/>

</ruleset>
